spring:
  data:
    mongodb:
      username: capellax
      password: 123456
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # for local development environment
        spring.json.type.mapping: orderConfirmation:com.capellax.ecommerce.kafka.order.OrderConfirmation, paymentConfirmation:com.capellax.ecommerce.kafka.payment.PaymentConfirmation
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest

  mail:
    host: localhost
    port: 1025
    username: capellax
    password: 123456
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
